GET http://localhost:3001/api/notes

### Single note test
GET http://localhost:3001/api/notes/1

### delete note
DELETE  http://localhost:3001/api/notes/3

### bad post request 
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}

### good post request 
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "testing functionality",
    "important": "true"
}


### middleware test
GET http://localhost:3001/222 HTTP/1.1


### update importance of existing note

PUT http://localhost:3001/api/notes/1